
* WHAT'S THIS ALL ABOUT?


This is an attempt to specify what data is available and what data is needed in order to 'stretch' PAPERMAP so that it matches the surveyed map information that we have.

Maybe
Step 0.1:
Select one castiron polygon at a time, with the corresponding papermap polygons, village points, and (ultimately) other features that are part of the consideration.  
NOTE - this will tear the papermap at castiron boundaries.
Step 0.2:
(Probably)
Determine the center of gravity or one extreme (say northernmost) point for the castiron polygon on the one hand and the group of papermap polygons corresponding to that castiron polygon on the other. 
Line them up.

Step 1:
Stretch PAPERMAP so that PAPERMAP mura boundaries match CASTIRON mura boundaries, wherever possible, and fail/cope gracefully where impossible/hard

Step 2:
(As a mostly separate step after step 1 has been completed for the whole map.)
Stretch papermap, (mostly) within each CASTIRON region separately, so as to:  

(2.1) Adjust PAPERMAP village boundaries to match to:
VILLAGEMAP village location info so that all villages are inside the correct PAPERMAP village_boundaries.

(2.2) Match other 'heuristic' things that we think make it more likely that the village boundaries are in the correct locations, or at least 'reasonable' locations.
These include: 
Boundaries being somewhat equidistant to villages and village districts being somewhat 'compact'.
Boundaries tending to follow LANDSCAPEMAP features, e.g. rivers, ridgelines, etc.
That the papermap not be distorted too much.


** Why this document is important

This is a tough problem.
Knowing what information may be *feasibly available* is necessary for planning how to 'solve' it in a useful manner.
Agreeing and verifying what information *will be* made available is absolutely vital.
There is no point writing a solver only to discover that the information it expects is not available (e.g. for other areas of Japan).

Where the information is specified as accurate, it must be accurate - and a way to efficiently correct any errors is needed.
Where the information is not always accurate, that must be specified also.
e.g. if names are specified as unique, then they must indeed be unique.
e.g. if villages are sometimes in the wrong castiron-region, then this must be stated so that the solver is written with this in mind.

The most efficient time to discover and define all this is as soon as possible.


* NAMES OF THINGS


VILLAGEPOINTS   - village locations
CASTIRON        - boundaries  Based on your nnet output. These are boundaries of the ~modern villages that comprise ca. 5-10 Edo-period villages whose boundaries we are after.  Regions are called 'mura'.
PAPERMAP        - boundaries  Edo-period villages whose boundaries we are after  -  a tracing of a “paper map” with Edo-period village boundaries that had to be rubbersheeted in georeferencing. 
AZAMAP          - boundaries  These are what my google doc calls aza: modern census districts. Werner has algorithmically eliminated those that we judged to be unlikely to preserve older boundaries.
LANDSCAPEMAP    - rivers, ridgelines, etc

TAG  - a type of information attached to some GIS objects, e.g. that all villages have a unique id, or that all castiron areas have the id of region they denote.
NODE - a point on the map with lat&lon (or easting-northing), and maybe other information e.g. TAGs.
AREA - a circular line with 3 or more points.  the AREA contains the ids of the points that make up the line, and maybe other information e.g. TAGs.


* DATA THAT IS AVAILABLE AND/OR NEEDED

** VILLAGEPOINTS
SURVEYED

consists of:
NODEs
The NODEs have TAG - village_id - unique names that *link-to* the same names in PAPERMAP village districts  [NOTE, FD calls TAG a ‘field’]
The NODEs have TAG - castiron_id    - unique names that *link-to* the same names in CASTIRON.

NOTE 2 villages can have the same village_id  - e.g. upper and lower parts of a village

NOTE - village_id 9999 seems to denote something special - FD says to discard villages with this village_id


** CASTIRON
SURVEYED

consists of:
NODEs & AREAs
AREASs have TAG - castiron_id

castiron_id is *always unique* to 1 cast-iron-region and *links-to* castiron_id used in PAPERMAP

NOTE CASTIRON regions are NOT always contiguous - i.e. we can get enclaves and exclaves.

also: RELATIONs - for when we have regions that have foreign enclaves inside them.
a RELATION lists the ids of several areas, with tags 'outer' and 'inner'


** PAPERMAP
NOT-SURVEYED

consists of:
NODEs and AREAs

AREAs have TAG - village_id that *link-to* the same names in VILLAGEMAP
AREAs have TAG - castiron_id    that *link-to* the same names in CASTIRON.  The castiron_id says what castiron region the AREA is inside.

NOTE village_regions are NOT always contiguous - i.e. we can get enclaves and exclaves.

also: RELATIONs - for when we have regions that have foreign enclaves inside them.
a RELATION lists the ids of several areas, with tags 'outer' and 'inner'


SOMETIMES, BUT NOT ALWAYS:
other information - e.g. 
rivers are sometimes present

NOTE - unlike everything else other than PAPERMAP, the NODEs in papermap WERE NOT SURVEYED
       Thus the locations are not reliable.
       But we think that relations between things in the paper map might be reliable - e.g. the topology of boundaries.

NOTE - since the solver will be 'stretching' this map, but distorting as little as possible given other constraints:
       The paper map should NOT be georeferenced (much), as this will distort the map in an unknown way.
       ONLY set the correct scale (this is important).  And attempt to (approximately) 'center the map' and get the orientation correct.


** AZAMAP
SURVEYED

consists of:
NODEs and AREAs

GE - not finished yet

NOTE BY FD:  Maybe useful as a note to George: these are the smallest modern units in the administrative hierarchy, and sometimes correspond to Edo-period villages. 
The version we will give you has been preselected to exclude those Aza that are less likely to preserve older boundaries. 
That selection was made based on the observation that areas that urbanized in the modern period often have aza that bear no relation to the old villages, 
while outlying areas often preserve their boundaries.


** RIVERMAP / LANDSCAPEMAP
SURVEYED

consists of:
NODEs & LINEs.

GE - not finished yet

Add extra TAGs here for you scoring methods.

NOTE - since all LANDSCAPEMAP features are in 1 shapefile, then the LINEs each need a TAG 
- e.g. river, ridgeline, etc.


NOTE BY FD:  If we give you water surfaces from a detailed land use survey, we would also be giving you areas. 
We know that such rivers are more likely to be consequential than our drainage polylines, which make no distinction between a rivulet and a large river. 
But if areas complicate the task, I am happy to just give you the drainage polyline. Again, I thought of this as a future step. 
The proof of concept could just use PAPERMAP, CASTIRON, and VILLAGEPOINTS. 
All the information exists, we just have to make a selection of what features to include and decide on the scoring method.
I think we discussed this, but I am also open to letting you assign the scores that yield the best results, by trial and error. 
Please remind me what your thinking is on that point.  #TODO
**LANDSCAPEPOINTS
SURVEYED
These are features like mountain peaks and river nodes (confluences) that we can match with the corresponding features on papermaps.

**PAPERMAPPOINTS
NOT SURVEYED
These are features like mountain peaks and river nodes and village centers available on some papermaps that we can require to be matched with LANDSCAPEPOINTS and VILLAGEPOINTS.

**PAPERMAPLINES
NOT SURVEYED
These are features like rivers and ridges on some of our papermaps. 
We may have to drop this feature, since the extra tracing work may bust of time budget and may greatly complicate your programming.

#TODO
Questions for George:
    (2) Did you want all the layers in one file, or just the natural features? 
I would advocate for keeping the following separate:
VILLAGEPOINTS
PAPERMAP
CASTIRON
AZAMAP
LANDSCAPELINES
LANDSCAPEPOINTS
PAPERMAPPOINTS
My reasoning is the following:
    (a) We may have to make corrections to these features as we go along, and it is inconvenient to have to re-combine all features whenever that happens.
    (b) More importantly: the coverage of these layers is not identical. 
VILLAGEPOINTS is either national (if we finish our review of locations in time) or prefectural (if we do not).
PAPERMAP and PAPERMAPPOINTS and PAPERMAPLINES are often prefectural, but sometimes separate for each district level or some other sub-prefectural entity.
CASTIRON, AZAMAP, LANDSCAPELINES, and LANDSCAPEPOINTS are national, but can be exported by prefecture if that is more convenient.
