
* WHAT'S THIS ALL ABOUT?


This is an attempt to specify what data is available and what data is needed in order to 'stretch' PAPERMAP so that it matches the surveyed map information that we have.


Step 1:
Stretch PAPERMAP so that PAPERMAP mura boundaries match CASTIRON mura boundaries, wherever possible, and fail/cope gracefully where impossible/hard

Step 2:
(As a mostly separate step after step 1 has been completed for the whole map.)
Stretch papermap, (mostly) within each CASTIRON region separately, so as to:  

(2.1) Adjust PAPERMAP village boundaries to match to:
VILLAGEMAP village location info so that all villages are inside the correct PAPERMAP village_boundaries.

(2.2) Match other 'heuristic' things that we think make it more likely that the village boundaries are in the correct locations, or at least 'reasonable' locations.
These include: 
Boundaries being somewhat equidistant to villages and village districts being somewhat 'compact'.
Boundaries tending to follow LANDSCAPE features, e.g. rivers, ridgelines, etc.
That the papermap not be distorted too much.


** Why this document is important

This is a tough problem.
Knowing what information may be *feasibly available* is necessary for planning how to 'solve' it in a useful manner.
Agreeing and verifying what information *will be* made available is absolutely vital.
There is no point writing a solver only to discover that the information it expects is not available (e.g. for other areas of Japan).

Where the information is specified as accurate, it must be accurate - and a way to efficiently correct any errors is needed.
Where the information is not always accurate, that must be specified also.
e.g. if names are specified as unique, then they must indeed be unique.
e.g. if villages are sometimes in the wrong castiron-region, then this must be stated so that the solver is written with this in mind.

The most efficient time to discover and define all this is as soon as possible.


* NAMES OF THINGS


VILLAGEPOINTS   - village locations
CASTIRON        - boundaries  Based on your nnet output. These are boundaries of the ~modern villages that comprise ca. 5-10 Edo-period villages whose boundaries we are after.  Regions are called 'mura'.
PAPERMAP        - boundaries  Edo-period villages whose boundaries we are after  -  a tracing of a “paper map” with Edo-period village boundaries that had to be rubbersheeted in georeferencing. 
AZAMAP          - boundaries  These are what my google doc calls aza: modern census districts. Werner has algorithmically eliminated those that we judged to be unlikely to preserve older boundaries.
LANDSCAPE       - rivers, ridgelines, etc

TAG  - a type of information attached to some GIS objects, e.g. that all villages have a unique id, or that all castiron areas have the id of region they denote.
NODE - a point on the map with lat&lon (or easting-northing), and maybe other information e.g. TAGs.
AREA - a circular line with 3 or more points.  the AREA contains the ids of the points that make up the line, and maybe other information e.g. TAGs.


* DATA THAT IS AVAILABLE AND/OR NEEDED

** VILLAGEPOINTS
SURVEYED

consists of:
NODEs
The NODEs have TAG - village_id - unique names that *link-to* the same names in PAPERMAP village districts  [NOTE, FD calls TAG a ‘field’]
The NODEs have TAG - castiron_id    - unique names that *link-to* the same names in CASTIRON.

NOTE 2 villages can have the same village_id  - e.g. upper and lower parts of a village

NOTE - village_id 9999 seems to denote something special - FD says to discard villages with this village_id


** CASTIRON
SURVEYED

consists of:
NODEs & AREAs
AREASs have TAG - castiron_id

castiron_id is *always unique* to 1 cast-iron-region and *links-to* castiron_id used in PAPERMAP

NOTE CASTIRON regions are NOT always contiguous - i.e. we can get enclaves and exclaves.

also: RELATIONs - for when we have regions that have foreign enclaves inside them.
a RELATION lists the ids of several areas, with tags 'outer' and 'inner'


** PAPERMAP
NOT-SURVEYED

consists of:
NODEs and AREAs

AREAs have TAG - village_id that *link-to* the same names in VILLAGEMAP
AREAs have TAG - castiron_id    that *link-to* the same names in CASTIRON.  The castiron_id says what castiron region the AREA is inside.

NOTE some papermap areas have NO village_id.  These are shared areas that somehow belong to several villages.  
     FD estimates that there are only approx 100-200 of these in the whole of Japan.  They still have castiron_id (of course).

NOTE village_regions are NOT always contiguous - i.e. we can get enclaves and exclaves.

NOTE we may have (very) rare cases of papermap areas that span 2 castiron regions.

also: RELATIONs - for when we have regions that have foreign enclaves inside them.
a RELATION lists the ids of several areas, with tags 'outer' and 'inner'


SOMETIMES, BUT NOT ALWAYS:
other information - e.g. 
rivers are sometimes present.  These may/will be in separate shapefiles - e.g. papermaplandscapeline.shp, etc.

NOTE - unlike everything else other than PAPERMAP, the NODEs in papermap WERE NOT SURVEYED
       Thus the locations are not reliable.
       But we think that relations between things in the paper map might be reliable - e.g. the topology of boundaries.

NOTE - since the solver will be 'stretching' this map, but distorting as little as possible given other constraints:
       The paper map should NOT be georeferenced (much), as this will distort the map in an unknown way.
       ONLY set the correct scale (this is important).  And attempt to (approximately) 'center the map' and get the orientation correct.


** AZAMAP
SURVEYED

consists of:
NODEs and AREAs

NOTE BY FD:  Maybe useful as a note to George: these are the smallest modern units in the administrative hierarchy, and sometimes correspond to Edo-period villages. 
The version we will give you has been preselected to exclude those Aza that are less likely to preserve older boundaries. 
That selection was made based on the observation that areas that urbanized in the modern period often have aza that bear no relation to the old villages, 
while outlying areas often preserve their boundaries.


** LANDSCAPE

SURVEYED

consists of:
NODEs & LINEs.
Maybe also AREAs


Add extra TAGs here for FD's scoring methods.

NOTE - since all LANDSCAPE features are in 1 shapefile (or maybe 3, if we have points, lines, and areas), then the LINEs each need a TAG 
- e.g. river, ridgeline, etc.


** Talk

NOTE BY FD:  If we give you water surfaces from a detailed land use survey, we would also be giving you areas. 
We know that such rivers are more likely to be consequential than our drainage polylines, which make no distinction between a rivulet and a large river. 
But if areas complicate the task, I am happy to just give you the drainage polyline. Again, I thought of this as a future step. 
The proof of concept could just use PAPERMAP, CASTIRON, and VILLAGEPOINTS. 
All the information exists, we just have to make a selection of what features to include and decide on the scoring method.
I think we discussed this, but I am also open to letting you assign the scores that yield the best results, by trial and error. 


* HOW THE DATA WILL BE SENT TO GE

As shapefiles:

GE would prefer as few shapefiles as is reasonably possible.  Note that FD says more is easier for Yale.
But would probably prefer to do Japan region-by-region rather than the whole country in 1 shapefile.
That way, he can say - "there are 3 errors in osaka region, can you correct them" etc.
Also, whole of Japan may be too large for GE's systems.

As a suggestion ...
For each region:
Surveyed data:
    villagepoints.shp    [points]   - vital
    castiron.shp         [areas]    - vital
    azamap.shp           [areas]
    landscapepoints.shp  [points] 
    landscapelines.shp   [lines]
    landscapeareas.shp   [areas]
Papermap data (i.e. data that will be 'moved about'):
    papermap.shp         [areas]    - vital
    papermaplandscapepoints.shp   [points] - these are e.g. mountain peaks    
    papermaplandscapelines.shp    [lines]  - these are e.g. rivers, ridgelines
    papermaplandscapeareas.shp    [areas]  - these are e.g. lakes, forests

